# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: hcorrale <hcorrale@student.42.fr>          +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2015/07/24 14:57:22 by hcorrale          #+#    #+#              #
#    Updated: 2015/07/24 15:15:00 by hcorrale         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file

SRC = main.c

GFLAG = -Wall -Wextra -Werror -o

all: $(NAME)

$(NAME):
	gcc $(GFLAG) $(NAME) $(SRC)

clean:
	rm -f $(NAME)

f_clean:
	clean
